services:
  mongodb:
    image: mongo:latest
    container_name: iamstar_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  chroma:
    image: chromadb/chroma:latest
    container_name: iamstar_chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/data/db

volumes:
  mongo-data:
  chroma-data: